export const init = (): void => {
  process.env.FIREBASE_AUTH_HOSTNAME =      process.env.NEXT_PUBLIC_FIREBASE_AUTH_HOSTNAME;
  process.env.FIREBASE_FIRESTORE_HOSTNAME = process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_HOSTNAME;
  process.env.FIREBASE_FUNCTIONS_HOSTNAME = process.env.NEXT_PUBLIC_FIREBASE_FUNCTIONS_HOSTNAME;
  process.env.FIREBASE_STORAGE_HOSTNAME =   process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_STORAGE_HOSTNAME;

  process.env.FIREBASE_AUTH_PORT =      process.env.NEXT_PUBLIC_FIREBASE_AUTH_PORT;
  process.env.FIREBASE_FIRESTORE_PORT = process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_PORT;
  process.env.FIREBASE_FUNCTIONS_PORT = process.env.NEXT_PUBLIC_FIREBASE_FUNCTIONS_PORT;
  process.env.FIREBASE_STORAGE_PORT =   process.env.NEXT_PUBLIC_FIREBASE_STORAGE_PORT;

  process.env.FIREBASE_AUTH_EMULATOR =      process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR;
  process.env.FIREBASE_FIRESTORE_EMULATOR = process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR;
  process.env.FIREBASE_FUNCTIONS_EMULATOR = process.env.NEXT_PUBLIC_FIREBASE_FUNCTIONS_EMULATOR;
  process.env.FIREBASE_STORAGE_EMULATOR =   process.env.NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR;
}

export default init