name: Package
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build
        run: npm run build:hooks
      - name: Publish
        run: npm publish packages/hooks/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
