name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main') # Publish it only if the push comes from the master branch
    strategy:
      matrix:
        {
          dir:
            [
              firebase-auth-next,
              firebase-functions,
              firebase-hooks,
              helpers,
              hooks,
            ],
        }
    defaults:
      run:
        working-directory: "packages/${{matrix.dir}}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get Current Version
        id: current
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        with:
          path: "packages/${{matrix.dir}}"
      - name: Check version changes
        uses: autsys/package-version@v0.0.9
        id: latest
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          owner: autsys
          repo: mono
          name: ${{matrix.dir}}
          debug: true
      - name: Versions detected
        run: 'echo "Version detected! Current: ${{ steps.current.outputs.current-version }}" Latest: ${{ steps.latest.outputs.version}}'
      - name: Compare Semantic Version
        id: compare
        uses: autsys/semver@v0.0.5
        with:
          a: ${{ steps.current.outputs.current-version }}
          b: ${{ steps.latest.outputs.version }}
      - name: Set up Node.js for GPR
        if: steps.compare.outputs.gt == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: "https://npm.pkg.github.com/"
          scope: "@autsys"
      # - name: Set up package for GPR # You need to make sure you package name has the scope needed for GPR
      #   if: steps.check.outputs.changed == 'true'
      #   run: npm run gpr-setup
      - name: Install dependencies
        if: steps.compare.outputs.gt == 'true'
        run: npm install --ignore-scripts
      - name: Publish package to GPR
        if: steps.compare.outputs.gt == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
