name: Package
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        {
          dir:
            [
              packages/firebase-auth-next,
              packages/firebase-functions,
              packages/firebase-hooks,
              packages/helpers,
              packages/hooks,
            ],
        }
    defaults:
      run:
        working-directory: ${{matrix.dir}}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Update npm
        run: sudo npm i -g npm
      - name: Build
        run: npm publish
